# fly.toml app configuration file generated for bestflix-server on 2023-08-06T16:09:27-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bestflix-server"
primary_region = "yyz"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
